### ISSUE TITLE
botocore explodes when installed alongside pyOpenSSL, ndg-httpsclient and pyasn1 

### ISSUE THREAD

**Issue by bhuber** [boto/botocore#266]
I'm not an expert with boto or botocore, so apologies in advance if this is a duplicate or whatever, but I can't find anything related in the issues on GH.  To reproduce, create a new virtualenv and do the following:

```sh
pip install pyOpenSSL==0.14 ndg-httpsclient==0.3.2 pyasn1==0.1.7 botocore==0.38
python
>>> import botocore.vendored.requests
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bhuber/envs/sandbox/local/lib/python2.7/site-packages/botocore/vendored/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/bhuber/envs/sandbox/local/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    orig_connectionpool_ssl_wrap_socket = connectionpool.ssl_wrap_socket
AttributeError: 'module' object has no attribute 'ssl_wrap_socket'
>>> 
```

This is a direct manifestation of a bug closed in requests==2.1.0: https://github.com/kennethreitz/requests/issues/1732 .  Updating the requests lib would probably fix it.

As a workaround, ```pip install pyopenssl==0.12``` currently fixes it for me.

**Comment by guss77** [comment]
I have the same problem with installing awscli on Ubuntu 15.04. I worked around by doing:

    sudo apt-get purge python-ndg-httpsclient
    sudo pip install ndg-httpsclient==0.3.1

**Comment by Rowanto** [comment]
Thanks @guss77 . I am using Debian testing, and those commands also fixed my eb cli. :+1:

**Comment by jdanbrown** [comment]
:boom: Thanks @jamesls!
- Works for me with `awscli==1.7.7` + `botocore==0.88.0` + `requests==2.5.1`
- Works with either `ndg-httpsclient==0.3.3` or `0.3.2`, but not with `0.3.1` like in my comment above

```sh
$ python --version
Python 2.7.7

$ pip freeze | ack -i '^(awscli|botocore|pyopenssl|pyasn1|ndg-httpsclient|requests)\='
awscli==1.7.7
botocore==0.88.0
ndg-httpsclient==0.3.3
pyOpenSSL==0.14
pyasn1==0.1.7
requests==2.5.1

$ aws --version
aws-cli/1.7.7 Python/2.7.7 Darwin/13.4.0

$ http head https://sni.velox.ch
HTTP/1.1 200 OK
Cache-Control: max-age=0
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
Date: Fri, 13 Feb 2015 06:49:51 GMT
Expires: Fri, 13 Feb 2015 06:49:51 GMT
Keep-Alive: timeout=15, max=100
Server: Apache/2.4
Strict-Transport-Security: max-age=10886400; includeSubDomains
```

**Comment by jarrettj** [comment]
@guss77 worked on ubuntu 15.04, Thanks.

**Comment by memosstilvi** [comment]
@guss77 worked on ubuntu 14.04, Thanks.
